### ISSUE TITLE
Enable Multiple accounts with same device with multiple spotifyd instances

### ISSUE THREAD

**Issue by maurice-schleussinger** [hassio-addons/addon-spotify-connect#26] opened 2019-03-01 22:44 UTC
As I can't comment on https://github.com/hassio-addons/addon-spotify-connect/issues/5:

It is possible to use multiple instances of this add-on to archive multiuser "support". It creates overlapping sounds which is fine for me.

So, what I did was creating my own add-on repository (https://github.com/maurice-schleussinger/repository, up to date as of 01.03.2019) and add just another instance of this add-on.

It would be nice to have at least this ~~dirty hack~~ workaround out of the box (you could spawn multiple instances of spotfiyd if there are multiple username/password blocks in the config for example.

<blockquote><img src="https://avatars0.githubusercontent.com/u/1615089?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/maurice-schleussinger/repository">maurice-schleussinger/repository</a></strong></div><div>Community Hass.io Add-ons for Home Assistant. Contribute to maurice-schleussinger/repository development by creating an account on GitHub.</div></blockquote>

**Comment by danielsteiner** [comment] 2019-03-02 06:48
I didn't take a look into the code but it I suppose this is based on a similar approach as https://github.com/dtcooper/raspotify which is a wrapper for Spotify Web Connect. The problem is that the underlying library (librespot) does not support this but this has been discussed there as well https://github.com/dtcooper/raspotify/issues/51

**Comment by frenck** [comment] 2019-03-04 12:11
Since the codebase the add-on uses does not support this, there is nowhere for me to go with this request. Therefore, closing it.

Nevertheless, thank you for your suggestion.

**Closed by frenck** 2019-03-04 12:11 UTC
